### ISSUE TITLE
ASIO401 is Windows only

### ISSUE THREAD

**Issue by brennmat** [dechamps/ASIO401#15]
ASIO401 would be much more useful if it would expose the QA40x devices as USB Audio Devices to Linux or Mac OS X.

**Comment by dechamps** [comment]
I'm not sure what you mean. As far as I know ASIO is not a thing (or at least not natively) on Linux or Mac OS X. Even if one were to build a native ASIO401 binary for Linux or Mac OS X it's not clear to me how an ASIO Host Application would even discover it, assuming such applications exist in the first place. I would be happy to be proven wrong.

(That said, I see no reason why ASIO401 wouldn't work under Wine, assuming that Wine has a working WinUSB implementation. But I presume that's not what your message is about.)

If what you're requesting is an actual native (not ASIO) OS audio device driver for Linux or Mac OS X, then I'm afraid that's a whole other ball game. I don't have the resources nor the motivation to do that, and it would be out of scope for the ASIO401 project anyway.

If someone else is interested in writing such a native driver, then I would gladly provide any help they might need when it comes to understanding the QA401 USB protocol, but I'm afraid my expertise does not extend to writing native audio drivers for various operating systems.
