### ISSUE TITLE
ADC noise floor takes 20+ seconds to stabilize when attenuator is off

### ISSUE THREAD

**Issue by dechamps** [dechamps/ASIO401#17]
With ASIO401 1.1, `attenuator = false`, and the QA401 inputs shorted, the following command:

```
ASIO401Test --record-to-file noisefloor.wav --buffer-switch-count 1600
```

Records a file whose amplitude over time looks like the following (left and right channel):

![qa401nf1](https://user-images.githubusercontent.com/866859/54495094-cd89b280-48d8-11e9-81ee-9119762667a7.png)
![qa401nf2](https://user-images.githubusercontent.com/866859/54495096-cf537600-48d8-11e9-9f40-cb45cc5cbbd9.png)

With the attenuator enabled the issue is still there, but much less pronounced (converges in about 1 second).

This is especially problematic for THD+N measurements, which suffer from an elevated noise floor if done too early after streaming starts.

**Comment by dechamps** [comment]
I am unable to reproduce this using the QA Analyzer application, even if disable the attenuator and start immediately after the application opens. Therefore this is not an inherent limitation of the hardware.

**Comment by dechamps** [comment]
Spectrum of the 0.5-5 second portion of the second graph above:

![spectrum](https://user-images.githubusercontent.com/866859/54495373-28bca480-48db-11e9-8567-08b84e993f24.png)

It's low-frequency noise, basically.

**Comment by dechamps** [comment]
Okay, so, it's basically a DC offset. If I run a 5 Hz highpass filter on the output, the noise floor stabilizes at around the 400 ms mark.

This could explain why the QA Analyzer app is fine - it might be applying a similar highpass filter behind the scenes.

**Comment by dechamps** [comment]
The release notes of [QA Analyzer 1.726](https://github.com/QuantAsylum/QA401/releases/tag/1.726) seem to mention a similar issue:

> If the attenuator state is changed via an API call, the API will pause for 500 mS IF a hardware change is needed. The relay is very fast (1-2 mS) but the longer wait is needed for DC settling.

**Comment by matttay** [comment]
Hi Etienne, around line 74 of qa401.cpp you will see the following:

    WriteRegister(4, 1);
    WriteRegister(4, 0);
    WriteRegister(4, 3);

The writing of the 0 (second line) resets the codec and will re-starts the DC zero'ing process. Ideally, you'd write the 0 when you first started the driver, and after that, you'd never need to do it again.

You could verify this by starting the QA401 app and take a few captures. That will ensure the codec was reset. Close that app, then build the asio driver with the first two lines shown above commented out. And then use that dll to do your experiment again. I think the settling tax won't have to be paid.

**Comment by QuantAsylum** [comment]
[sorry, reposting from work account so I don't miss notifications]

Hi Etienne, around line 74 of qa401.cpp you will see the following:

     WriteRegister(4, 1); 
     WriteRegister(4, 0);
     WriteRegister(4, 3);

The writing of the 0 (second line) resets the codec and will re-starts the DC zero'ing process. Ideally, you'd write the 0 when you first started the driver, and after that, you'd never need to do it again.

You could verify this by starting the QA401 app and take a few captures. That will ensure the codec was reset. Close that app, then build the asio driver with the first two lines shown above commented out. And then use that dll to do your experiment again. I think the settling tax won't have to be paid.

**Comment by dechamps** [comment]
It's been a while, but it so happened I had a reason to pull out my QA401 today, so I took the opportunity to have another look at this issue.

I think one thing that might have caused confusion here is that I was under the impression that the QuantAsylum Analyzer application was immune to this problem. However it seems I was mistaken, as the following screencap demonstrates:

![qa401](https://user-images.githubusercontent.com/866859/146652773-6e4fb8bd-fb00-4070-b2ee-8ebb30c6fc4e.gif)

In the above, the first measurement immediately after starting is -97dBFS(L)/-80dBFS(R) and we only settle onto the final noise floor of about -130dBFS after ~20 seconds… which is precisely what my original report shows for ASIO401.

I can also reproduce this in the QuantAsylum Analyzer app simply by switching attenuator on and then off again. It clearly seems this is a limitation of the hardware, which takes a long time to get rid of DC after the attenuator is turned off.

So it looks like ASIO401 is behaving in exactly the same way as the official application does. Therefore I see no reason to see this as a bug in ASIO401.
