### ISSUE TITLE
Support for newer analysers 

### ISSUE THREAD

**Issue by ddavidebor** [dechamps/ASIO401#23]
Hi, 

would you be up for supporting the QA403x as well ?

**Comment by dechamps** [comment]
I wouldn't expect that to happen any time soon. I don't have a QA403 on hand and I am not working on projects that would justify the use of one these days.

**Comment by ddavidebor** [comment]
I might have a crack at it… 
may I pick your brain… does it look like it broadly works in the same way ? https://github.com/QuantAsylum/QA40x_BareMetal

**Comment by dechamps** [comment]
Looks like it at first glance. The "magic incantations" (USB register writes) look different, but the overall principle (write registers, read/write samples on a separate pipe) appears to be the same. You may be able to make ASIO401 work with this with relatively few changes.

**Comment by dechamps** [comment]
Matt Taylor from QuantAsylum convinced me to spend some time on this. I should be able to get started on QA403 support in a couple of weeks or so.

**Comment by ddavidebor** [comment]
Thank you so much for this ! I'll finally be able to get an Audio Analyzer that works with all my favourite software and is within budget.

**Comment by dechamps** [comment]
I am pleased to report that I'm pretty much done implementing QA403 (and QA402) support in ASIO401. I still have a few loose ends to tie up before I make an official release, but in the mean time, the curious (or impatient) can give it a try by downloading the  a5640381c14bae8ac18b937621ae89b0169a6243 development version - an installer can be found [here](https://github.com/dechamps/ASIO401/actions/runs/8971059004) and the corresponding updated docs are [here](https://github.com/dechamps/ASIO401/blob/asio401-1.1-62-ga564038/README.md) (note in particular the revamped [attenuator options](https://github.com/dechamps/ASIO401/blob/asio401-1.1-62-ga564038/CONFIGURATION.md#option-fullscaleinputleveldbv)).

If you do give this a try, I would be interested in any feedback as to whether it's working for you or not.

**Comment by ddavidebor** [comment]
Amazing, thank you very much ! I'll buy a QA403 asap and try it out

**Comment by dechamps** [comment]
This has been officially implemented in [ASIO401 2.0](https://github.com/dechamps/ASIO401/releases/tag/asio401-2.0). Enjoy!
